# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

Eight weeks in total. 4 hours per day, 4 days per week (16 hrs/wk * 8 weeks = 128 hrs)

- Phase 1: Creating mutations: AST tooling and mutant package functions for creating mutants - package astr
  - Weeks 1-2 (32 hrs)
- Phase 2:  Implement queueing tooling to be able to run many R sessions in parallel
  - Weeks 3-6 (64 hrs)
- Phase 3: Implement reporting tooling for showing results of mutation testing and pointing out where mutations occurred in the code and what the mutation may indicate
  - Week 7 (16 hrs)
- Phase 4: Write detailed package level documentation as well as detailed vignettes, including a tutorial for a very small hello world example to get users oriented, as well as a tutorial for a larger package with a lot of code and tests to demonstrate solutions for saving time, running on CI, and more
  - Week 8 (16 hrs)


## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->
